//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorTrackingSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distinct
    {
        public int DistinctId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string DistinctName { get; set; }
    }
}
