//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorTrackingSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ErrorTypes()
        {
            this.ErrorInformation = new HashSet<ErrorInformation>();
        }
    
        public int ErrorTypeId { get; set; }
        public string ErrorTypeName { get; set; }
        public string ErrorTypeExplanation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErrorInformation> ErrorInformation { get; set; }
    }
}
