//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorTrackingSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorInformation
    {
        public int ErrorId { get; set; }
        public Nullable<int> ErrorTypeId { get; set; }
        public string ErrorSummary { get; set; }
        public string ErrorDetails { get; set; }
        public string Image { get; set; }
        public string ErrorSolution { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ErrorTypes ErrorTypes { get; set; }
    }
}
